import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Bebas_Neue } from "next/font/google";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const bebas_neue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400", // Bebas Neue is typically available in 400 weight
  variable: "--font-bebas-neue", // 3. Define the CSS variable
});
export const metadata: Metadata = {
  title: "Caixa Épica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${inter.variable} ${bebas_neue.variable} antialiased`}
        >
          {children}
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
